version: '3.9'

services:

  inferenceServerGRPC:
    build:
      context: .
      dockerfile: BuildGRPCServer.Dockerfile
    image: codeadeel/face:grpcserver
    container_name: faceGRPCServer
    hostname: facegrpcinference
    expose:
      - 8080
    volumes:
      - ./Resources/face_detect_Nx3x640x640.onnx:/face_detect_Nx3x640x640.onnx:ro
      - ./Resources/face_landmark_Nx3x160x160.onnx:/face_landmark_Nx3x160x160.onnx:ro
      - ./Resources/face_recognition_Nx3x112x112.onnx:/face_recognition_Nx3x112x112.onnx:ro
      - ./Resources/anti-spoof_1x3x128x128.onnx:/anti-spoof_1x3x128x128.onnx:ro
    environment:
      - targetWidth=640
      - targetHeight=640
      - landmarkWidth=160
      - landmarkHeight=160
      - recognitionWidth=112
      - recognitionHeight=112
      - spoofHeight=128
      - spoofWidth=128
      - invalidThreshold=0.75
      - facesTemplatesBucket=facebook
      - detectionModel=/face_detect_Nx3x640x640.onnx
      - landmarkModel=/face_landmark_Nx3x160x160.onnx
      - recognitionModel=/face_recognition_Nx3x112x112.onnx
      - spoofingModel=/anti-spoof_1x3x128x128.onnx
      - bucketAccessKey=2sBzBQccV3xFjBRgfX5G
      - bucketSecretKey=AULQoQDHnTkr5u95ECvUDjCR1X3RvX6j7tlmXVQT
      - secureBucket=false
      - bucketUrl=facebuckets:9000
      - serverIp=[::]:8080
      - messageLength=1000000000
      - numWorkers=1
    networks:
      - faceNetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - bucketStorage
    profiles:
      - fullInference
      - minimal

  inferenceServerREST:
    build:
      context: .
      dockerfile: BuildRESTServer.Dockerfile
    image: codeadeel/face:restserver
    container_name: faceRESTServer
    hostname: facerestinference
    expose:
      - 8080
    environment:
      - grpcServerIP=facegrpcinference:8080
      - imageWidth=640
      - imageHeight=640
      - inferencePort=8080
      - apiRoute=/face
    networks:
      - faceNetwork
    depends_on:
      - inferenceServerGRPC
    profiles:
      - fullInference

  liveDemoFace:
    build:
      context: .
      dockerfile: BuildLiveDemo.Dockerfile
    image: codeadeel/face:livedemo
    container_name: faceLiveDemo
    hostname: facelivedemo
    expose:
      - 8080
    environment:
      - meshModel=/home/faceMesh.task
      - serverIP=facegrpcinference:8080
    networks:
      - faceNetwork
    depends_on:
      - inferenceServerGRPC
      - bucketStorage
    profiles:
      - fullInference
      - minimal
  
  enrollFace:
    build:
      context: .
      dockerfile: BuildEnrollment.Dockerfile
    image: codeadeel/face:enrollment
    container_name: faceEnrollment
    hostname: faceenrollment
    expose:
      - 8080
    environment:
      - submissionCode=faces12345
      - facesTemplatesBucket=facebook
      - bucketAccessKey=2sBzBQccV3xFjBRgfX5G
      - bucketSecretKey=AULQoQDHnTkr5u95ECvUDjCR1X3RvX6j7tlmXVQT
      - secureBucket=false
      - bucketUrl=facebuckets:9000
      - serverIP=facegrpcinference:8080
    networks:
      - faceNetwork
    depends_on:
      - inferenceServerGRPC
      - bucketStorage
    profiles:
      - fullInference
      - minimal
  
  bucketStorage:
    image: minio/minio@sha256:cde7d0beaa150ec9f3323f9432c73794b43496176ae4d0bb4898625e0b7fe51b
    container_name: bucketStorageFace
    hostname: facebuckets
    command: server /data --console-address ":9001"
    expose:
      - 9000
      - 9001
    volumes:
    # Storage for Buckets
      - faceMINIOBucket:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=face1234
    networks:
      - faceNetwork
    profiles:
      - fullInference
      - minimal
  
  virtRouter:
    image: nginx@sha256:08bc36ad52474e528cc1ea3426b5e3f4bad8a130318e3140d6cfe29c8892c7ef
    container_name: faceRouter
    hostname: facerouter
    ports:
      - 1241:1200 # GRPC & REST Inference Server
      - 1243:1300 # Storage Bucket API
      - 1244:1301 # Storage Bucket Console
      - 1245:1400 # Live Demo (/livedemo), Face Enrollment (/enroll)
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./NGINX/face.crt:/home/face.crt:ro
      - ./NGINX/face.key:/home/face.key:ro
    networks:
      - faceNetwork
    depends_on:
      - inferenceServerGRPC
      - bucketStorage
    profiles:
      - fullInference
      - minimal
  
  faceTrainer:
    build:
        context: .
        dockerfile: BuildTrainer.Dockerfile
    image: codeadeel/face:trainer
    container_name: faceTrainer
    hostname: facetrainer
    volumes:
      - ./Data:/data
      - ./Resources:/output
    environment:
      - batchSize=10
      - epochs=10
      - workers=8
    networks:
      - faceNetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - trainer

networks:
  faceNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.1/16

volumes:
  faceMINIOBucket:
