# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceCommunication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x61\x63\x65\x43ommunication.proto\"\xa8\x02\n\x0bserverInput\x12\x0c\n\x04imgs\x18\x01 \x01(\x0c\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\x05\x12\x10\n\x08\x64\x61taType\x18\x06 \x01(\t\x12\x1b\n\x13\x64\x65tectionConfidence\x18\x07 \x01(\t\x12\x14\n\x0cnmsThreshold\x18\x08 \x01(\t\x12\x12\n\nboxCushion\x18\t \x01(\t\x12\x0f\n\x07\x62oxArea\x18\n \x01(\t\x12\x12\n\nrecogThres\x18\x0b \x01(\t\x12\x11\n\tfakeThres\x18\x0c \x01(\t\x12\x15\n\rtrackerFrames\x18\r \x01(\t\x12\x12\n\ntrackerIds\x18\x0e \x01(\t\x12\x10\n\x08\x63lientId\x18\x0f \x01(\t\"\x1f\n\x0cserverOutput\x12\x0f\n\x07results\x18\x01 \x01(\t27\n\x0b\x66\x61\x63\x65Service\x12(\n\tinference\x12\x0c.serverInput\x1a\r.serverOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faceCommunication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SERVERINPUT']._serialized_start=28
  _globals['_SERVERINPUT']._serialized_end=324
  _globals['_SERVEROUTPUT']._serialized_start=326
  _globals['_SERVEROUTPUT']._serialized_end=357
  _globals['_FACESERVICE']._serialized_start=359
  _globals['_FACESERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
