#!/usr/bin/env python3

"""
MODEL INFERENCE SERVER (GRPC)
=============================

Following program is used to perform inference on subject data using GRPC
"""

# %%
# Importing Libraries
from faceTools import *
import sys
from concurrent import futures
import socket
import json
import grpc
import faceCommunication_pb2
import faceCommunication_pb2_grpc

# %%
# GRPC Inference Class
class faceService(faceCommunication_pb2_grpc.faceServiceServicer):
    def __init__(self, *args, **kwargs) -> None:
        """
        This method is used to initialize GRPC service class
        """
        self.clientPool = dict()
    
    def __requestProcessor__(self, inpReq: faceCommunication_pb2.serverInput) -> tuple:
        """
        This method is used to process input request

        Arguments
        =========
        inpReq : Input request by client to process

        Outputs
        =======
        Image stack, Detection Confidence, NMS-Threshold, Box Cushion, Recognition Threshold, Anti-Spoofing Threshold, Number of frames to track, Stream ID, Client ID
        """
        retData = np.frombuffer(inpReq.imgs, dtype=inpReq.dataType).reshape(inpReq.batch, inpReq.height, inpReq.width, inpReq.channel)
        detectionConfidence = json.loads(inpReq.detectionConfidence)
        nmsThreshold = json.loads(inpReq.nmsThreshold)
        boxCushion = json.loads(inpReq.boxCushion)
        boxArea = json.loads(inpReq.boxArea)
        recogThres = json.loads(inpReq.recogThres)
        fakeThres = json.loads(inpReq.fakeThres)
        trackerFrames = json.loads(inpReq.trackerFrames)
        trackerIds = json.loads(inpReq.trackerIds)
        return retData, detectionConfidence, nmsThreshold, boxCushion, boxArea, recogThres, fakeThres, trackerFrames, trackerIds, inpReq.clientId
    
    def inference(self, request, context) -> faceCommunication_pb2.serverOutput:
        """
        This method is used to perform inference on the subject requst & returns response

        Arguments
        =========
        request : Request genetated in GRPC client
        context : Context generated by GRPC client

        Outputs
        =======
        GRPC output object
        """
        retData, detectionConfidence, nmsThreshold, boxCushion, boxArea, recogThres, fakeThres, trackerFrames, trackerIds, clientId = self.__requestProcessor__(request)
        if clientId not in list(self.clientPool.keys()):
            self.clientPool[clientId] = streamClient(clientId)
        inferRes = self.clientPool[clientId](inferenceInfer, retData, detectionConfidence, nmsThreshold, boxCushion, boxArea, recogThres, fakeThres, trackerFrames, trackerIds)
        return faceCommunication_pb2.serverOutput(results = json.dumps(inferRes))

# %%
# Execution
if __name__=='__main__':
    inferenceInfer = Inference()
    serverIp = os.environ.get('serverIp', '[::]:1234')
    messageLen = int(os.environ.get('messageLength', '1000000000'))
    numWorkers = int(os.environ.get('numWorkers', '1'))
    hostName = socket.gethostbyname(socket.gethostname())
    print(f"""
    ================================================================================
    | Face Detection, Recogntion, Anti-Spoofing & Tracking Inference Server (GRPC) |
    ================================================================================
    Server IP: {hostName}
    Maximum Server Communication Length: {messageLen}
    Number of Workers Allowed for GRPC Server: {numWorkers}
    -----------------------------------------
    >>>>> Press Ctrl+C To Shutdown Server

    ===================================================
    |                 Inference Logs                  |
    ===================================================
    """)
    serverOpts = [('grpc.max_send_message_length', messageLen), ('grpc.max_receive_message_length', messageLen)]
    server = grpc.server(futures.ThreadPoolExecutor(max_workers = numWorkers), options = serverOpts)
    faceCommunication_pb2_grpc.add_faceServiceServicer_to_server(faceService(), server)
    server.add_insecure_port(serverIp)
    server.start()
    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        print("""
    ===================================================
    |                   Shutting Down                 |
    ===================================================
    """)
        sys.exit(0)
        