events {
    worker_connections   1000;
}

http {

    # Inference Server
    server {
        listen       1200;
        listen  [::]:1200;

        location / {
            grpc_pass facegrpcinference:8080;
            client_max_body_size 10G;
        }

        location /face {
            proxy_pass http://facerestinference:8080/face;
            client_max_body_size 1G;
        }
    }

    # Basic Tools
    server {
        listen       1400 ssl;
        listen  [::]:1400 ssl;
        server_name localhost 127.0.0.1;
        ssl_certificate /home/face.crt;
        ssl_certificate_key /home/face.key;

        location /livedemo {
            proxy_pass http://facelivedemo:8080/livedemo;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            client_max_body_size 50M;
        }

        location /enroll {
            proxy_pass http://faceenrollment:8080/enroll;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            client_max_body_size 50M;
        }
    }

    # Bucket Storage
    ## Storage API
    server {
        listen       1300 ssl;
        listen  [::]:1300 ssl;
        server_name localhost 127.0.0.1;
        ssl_certificate /home/face.crt;
        ssl_certificate_key /home/face.key;

        ignore_invalid_headers off;
        client_max_body_size 5G;
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
            proxy_pass http://facebuckets:9000/;
        }
    }
    ## Storage Console
    server {
        listen       1301 ssl;
        listen  [::]:1301 ssl;
        server_name localhost 127.0.0.1;
        ssl_certificate /home/face.crt;
        ssl_certificate_key /home/face.key;
        
        ignore_invalid_headers off;
        client_max_body_size 5G;
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;
            real_ip_header X-Real-IP;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            chunked_transfer_encoding off;
            proxy_pass http://facebuckets:9001/;
        }
    }
}